variables:
# B - batch mode
# nsu - Suppress SNAPSHOT updates
# T - thread count (1C -> 1 thread)
    MVN_OPTS: "-B -nsu -T 1C"
stages:
    - build
maven:
    stage: build
    script: 
        - mvn $MVN_OPTS clean compile test
    tags:
        - jdk8



