variables:
# B - batch mode
# nsu - Suppress SNAPSHOT updates
# T - thread count (1C -> 1 thread)
    MVN_OPTS: "-B -nsu -T 1C"
stages:
    - Build
    - Test
compile:
    stage: Build
    script: 
        - mvn $MVN_OPTS clean compile test
    tags:
        - jdk8
test:
    stage: Test
    script:
        - mvn test
    tags:
        - jdk8
